api:
  bind-address: ":8086"
  auth-enabled: false

data:
  dir: "/var/lib/influxdb2"
  wal-dir: "/var/lib/influxdb2/wal"
  series-id-set-cache-size: 100

logging:
  level: info

meta:
  dir: "/var/lib/influxdb2/meta"
