# AgentForge Backend Application Configuration
# Environment: Development

spring:
  application:
    name: agentforge-backend
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/agentforge
    username: ${DB_USERNAME:agentforge}
    password: ${DB_PASSWORD:agentforge}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      # Connection retry settings for Docker environment
      connection-test-query: SELECT 1
      validation-timeout: 10000
      leak-detection-threshold: 60000
      # Additional connection properties for debugging
      connection-init-sql: SELECT 1
      initialization-fail-timeout: -1
      # Connection validation
      validation-interval: 30000
      minimum-idle: 1
      # Connection pool behavior
      auto-commit: true
      read-only: false
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: ${DEBUG:false}
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 1000ms
  
  # Security Configuration
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}
      roles: ADMIN
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false

# Server Configuration
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:development}

# Logging Configuration
logging:
  level:
    root: INFO
    com.agentforge: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: ${DEBUG:false}
    org.hibernate.type.descriptor.sql.BasicBinder: ${DEBUG:false}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/agentforge-backend.log
    max-size: 100MB
    max-history: 30

# AI Configuration
ai:
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: gpt-4o
    max-tokens: 4000
    temperature: 0.7
    timeout: 30000
  langchain:
    enabled: true
    model-provider: openai
    embedding-model: text-embedding-3-small
    vector-dimension: 1536

# Database Vector Configuration
vector:
  pgvector:
    enabled: true
    dimension: 1536
    similarity-metric: cosine

# Time Series Database Configuration
influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:}
  org: ${INFLUXDB_ORG:agentforge}
  bucket: ${INFLUXDB_BUCKET:agentforge-metrics}
  retention-policy: 30d

# Feature Flags
features:
  ai-generation: true
  ai-analysis: true
  compliance-checking: true
  real-time-monitoring: true
  advanced-analytics: true

# Performance Configuration
performance:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 100
    keep-alive-seconds: 60
  cache:
    default-ttl: 3600
    max-size: 1000

# Security Configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-change-in-production}
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    collection-interval: 60000 # 1 minute
  tracing:
    enabled: true
    sampling-rate: 0.1
  alerting:
    enabled: true
    webhook-url: ${ALERT_WEBHOOK_URL:}

# Development Configuration
development:
  debug: ${DEBUG:false}
  hot-reload: true
  mock-data: ${MOCK_DATA:false}
  test-mode: false
